version: "3"
services:
  database:
    image: postgres
    port:
      - 5432:5432
    restart:
      always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
