version: "3"
services:
  database:
    image: postgres:alpine
    ports:
      - 5432:5432
    restart:
      always
    environment:
      POSTGRES_USER: animanga
      POSTGRES_PASSWORD: animanga
      POSTGRES_DB: animanga
