version: "3"
services:
  database:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    restart:
      always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
