version: "3"
services:
  atta:
    image: postgres:alpine
    ports:
      - 5432:5432
    restart:
      always
    user:
      postgres # this user will create the above user
    environment: # docker exec -it dbtemplate_database_1 psql -U animanga
      POSTGRES_USER: animanga
      POSTGRES_PASSWORD: animanga
      POSTGRES_DB: animanga
